/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BudgetCategory = { 'food' : null } |
  { 'misc' : null } |
  { 'transport' : null } |
  { 'activities' : null } |
  { 'accommodation' : null };
export interface Expense {
  'id' : string,
  'date' : Time,
  'tripId' : string,
  'user' : Principal,
  'description' : string,
  'category' : BudgetCategory,
  'amount' : number,
}
export type Time = bigint;
export interface TravelNote {
  'id' : string,
  'title' : string,
  'content' : string,
  'createdAt' : Time,
  'tripId' : string,
  'user' : Principal,
  'category' : string,
}
export interface UserProfile {
  'interests' : Array<string>,
  'budgetPreference' : number,
  'name' : string,
  'email' : string,
  'preferredDestinations' : Array<string>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addExpense' : ActorMethod<[string, BudgetCategory, number, string], string>,
  'addTravelNote' : ActorMethod<[string, string, string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteTravelNoteById' : ActorMethod<[string], undefined>,
  'filterExpensesByDateRange' : ActorMethod<
    [string, Time, Time],
    Array<Expense>
  >,
  'filterNotesByCategory' : ActorMethod<[string, string], Array<TravelNote>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getExpenseSummariesByRange' : ActorMethod<
    [string, Time, Time],
    Array<Expense>
  >,
  'getExpensesByCategory' : ActorMethod<
    [string, BudgetCategory],
    Array<Expense>
  >,
  'getExpensesInAmountRange' : ActorMethod<
    [string, number, number],
    Array<Expense>
  >,
  'getNotesWithContentLength' : ActorMethod<
    [string, bigint],
    Array<TravelNote>
  >,
  'getTripBudget' : ActorMethod<
    [string, BudgetCategory],
    [] | [{ 'category' : BudgetCategory, 'amount' : number }]
  >,
  'getTripExpenses' : ActorMethod<[string], Array<Expense>>,
  'getTripNotes' : ActorMethod<[string], Array<TravelNote>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTripBudget' : ActorMethod<[string, BudgetCategory, number], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];