/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const BudgetCategory = IDL.Variant({
  'food' : IDL.Null,
  'misc' : IDL.Null,
  'transport' : IDL.Null,
  'activities' : IDL.Null,
  'accommodation' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Expense = IDL.Record({
  'id' : IDL.Text,
  'date' : Time,
  'tripId' : IDL.Text,
  'user' : IDL.Principal,
  'description' : IDL.Text,
  'category' : BudgetCategory,
  'amount' : IDL.Float64,
});
export const TravelNote = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
  'tripId' : IDL.Text,
  'user' : IDL.Principal,
  'category' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'interests' : IDL.Vec(IDL.Text),
  'budgetPreference' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'preferredDestinations' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addExpense' : IDL.Func(
      [IDL.Text, BudgetCategory, IDL.Float64, IDL.Text],
      [IDL.Text],
      [],
    ),
  'addTravelNote' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteTravelNoteById' : IDL.Func([IDL.Text], [], []),
  'filterExpensesByDateRange' : IDL.Func(
      [IDL.Text, Time, Time],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'filterNotesByCategory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(TravelNote)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getExpenseSummariesByRange' : IDL.Func(
      [IDL.Text, Time, Time],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesByCategory' : IDL.Func(
      [IDL.Text, BudgetCategory],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getExpensesInAmountRange' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Vec(Expense)],
      ['query'],
    ),
  'getNotesWithContentLength' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(TravelNote)],
      ['query'],
    ),
  'getTripBudget' : IDL.Func(
      [IDL.Text, BudgetCategory],
      [
        IDL.Opt(
          IDL.Record({ 'category' : BudgetCategory, 'amount' : IDL.Float64 })
        ),
      ],
      ['query'],
    ),
  'getTripExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
  'getTripNotes' : IDL.Func([IDL.Text], [IDL.Vec(TravelNote)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTripBudget' : IDL.Func([IDL.Text, BudgetCategory, IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const BudgetCategory = IDL.Variant({
    'food' : IDL.Null,
    'misc' : IDL.Null,
    'transport' : IDL.Null,
    'activities' : IDL.Null,
    'accommodation' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Expense = IDL.Record({
    'id' : IDL.Text,
    'date' : Time,
    'tripId' : IDL.Text,
    'user' : IDL.Principal,
    'description' : IDL.Text,
    'category' : BudgetCategory,
    'amount' : IDL.Float64,
  });
  const TravelNote = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
    'tripId' : IDL.Text,
    'user' : IDL.Principal,
    'category' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'interests' : IDL.Vec(IDL.Text),
    'budgetPreference' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'preferredDestinations' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addExpense' : IDL.Func(
        [IDL.Text, BudgetCategory, IDL.Float64, IDL.Text],
        [IDL.Text],
        [],
      ),
    'addTravelNote' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteTravelNoteById' : IDL.Func([IDL.Text], [], []),
    'filterExpensesByDateRange' : IDL.Func(
        [IDL.Text, Time, Time],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'filterNotesByCategory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(TravelNote)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getExpenseSummariesByRange' : IDL.Func(
        [IDL.Text, Time, Time],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesByCategory' : IDL.Func(
        [IDL.Text, BudgetCategory],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getExpensesInAmountRange' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Vec(Expense)],
        ['query'],
      ),
    'getNotesWithContentLength' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(TravelNote)],
        ['query'],
      ),
    'getTripBudget' : IDL.Func(
        [IDL.Text, BudgetCategory],
        [
          IDL.Opt(
            IDL.Record({ 'category' : BudgetCategory, 'amount' : IDL.Float64 })
          ),
        ],
        ['query'],
      ),
    'getTripExpenses' : IDL.Func([IDL.Text], [IDL.Vec(Expense)], ['query']),
    'getTripNotes' : IDL.Func([IDL.Text], [IDL.Vec(TravelNote)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTripBudget' : IDL.Func([IDL.Text, BudgetCategory, IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };